# Generated by Django 3.2.11 on 2022-03-16 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StockTable',
            fields=[
                ('stock_ts', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('stock_symbol', models.CharField(max_length=6)),
                ('stock_name', models.CharField(max_length=50)),
                ('stock_industry', models.CharField(max_length=45)),
                ('stock_market', models.CharField(max_length=45)),
                ('stock_list_date', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'stock_table',
            },
        ),
    ]
