# Generated by Django 3.2.11 on 2022-03-18 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockDailyTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_ts', models.CharField(max_length=10)),
                ('stock_daily_date', models.DateField()),
                ('stock_daily_open', models.DecimalField(decimal_places=2, max_digits=6)),
                ('stock_daily_high', models.DecimalField(decimal_places=2, max_digits=6)),
                ('stock_daily_low', models.DecimalField(decimal_places=2, max_digits=6)),
                ('stock_daily_close', models.DecimalField(decimal_places=2, max_digits=6)),
                ('stock_daily_pclose', models.DecimalField(decimal_places=2, max_digits=6)),
                ('stock_daily_change', models.DecimalField(decimal_places=2, max_digits=6)),
                ('stock_daily_pct', models.DecimalField(decimal_places=2, max_digits=6)),
                ('stock_daily_vol', models.DecimalField(decimal_places=2, max_digits=20)),
                ('stock_daily_amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.stocktable')),
            ],
        ),
    ]
