# Generated by Django 3.2.11 on 2022-03-18 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_stockdailytable'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='stockdailytable',
            table='stock_daily_table',
        ),
    ]
