# Generated by Django 3.2.11 on 2022-03-18 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_alter_stockdailytable_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stockdailytable',
            options={'ordering': ['stock_ts']},
        ),
        migrations.AlterModelOptions(
            name='stocktable',
            options={'ordering': ['stock_ts']},
        ),
    ]
