# Generated by Django 3.2.11 on 2022-03-18 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_auto_20220318_2208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockdailytable',
            name='stock',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stock.stocktable'),
        ),
    ]
