# Generated by Django 3.2.11 on 2022-03-18 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0005_alter_stockdailytable_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocktable',
            name='stock_industry',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='stocktable',
            name='stock_market',
            field=models.CharField(max_length=45, null=True),
        ),
    ]
