# Generated by Django 3.2.11 on 2022-04-19 02:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tradingSystem', '0001_initial'),
        ('stock', '0006_auto_20220318_2328'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockOptionalTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stock.stocktable')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tradingSystem.usertable')),
            ],
            options={
                'db_table': 'stock_optional_table',
            },
        ),
    ]
