# Generated by Django 3.2.11 on 2022-04-21 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0007_stockoptionaltable'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockUpdateTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_update_type', models.CharField(max_length=45)),
                ('stock_update_date', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'stock_update_table',
            },
        ),
    ]
