# Generated by Django 3.2.11 on 2022-03-16 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_title', models.CharField(max_length=100)),
                ('news_content', models.TextField()),
                ('news_time', models.DateTimeField()),
                ('news_src', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'news_table',
                'ordering': ['-news_time'],
            },
        ),
    ]
