# Generated by Django 3.2.11 on 2022-03-15 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_rename_news_source_newstable_news_src'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newstable',
            options={'ordering': ['-news_time']},
        ),
    ]
