# Generated by Django 3.2.11 on 2022-03-09 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commenttable',
            old_name='comment_stock_ts',
            new_name='comment_stock',
        ),
        migrations.RenameField(
            model_name='commenttable',
            old_name='comment_user_id',
            new_name='comment_user',
        ),
    ]
