# Generated by Django 3.2.11 on 2022-03-16 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commenttable',
            options={'ordering': ['-comment_time']},
        ),
        migrations.AlterModelOptions(
            name='discusstable',
            options={'ordering': ['-discuss_time']},
        ),
        migrations.AlterModelTable(
            name='discusstable',
            table='discuss_table',
        ),
    ]
