# Generated by Django 3.2.11 on 2022-03-10 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tradingSystem', '0001_initial'),
        ('community', '0002_auto_20220309_2321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commenttable',
            name='comment_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='DiscussTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discuss_content', models.CharField(max_length=100)),
                ('discuss_time', models.DateTimeField(auto_now=True)),
                ('discuss_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='community.commenttable')),
                ('discuss_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tradingSystem.usertable')),
            ],
        ),
    ]
