# Generated by Django 3.2.11 on 2022-02-27 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_no', models.CharField(max_length=18)),
                ('user_name', models.CharField(max_length=45)),
                ('password', models.CharField(max_length=45)),
                ('user_sex', models.CharField(max_length=5)),
                ('phone_number', models.CharField(max_length=45, unique=True)),
                ('user_email', models.EmailField(max_length=254)),
                ('photo_url', models.CharField(max_length=45)),
                ('account_num', models.CharField(max_length=45)),
                ('account_type', models.CharField(max_length=45)),
                ('account_balance', models.FloatField(null=True)),
                ('freeze', models.BooleanField(default=False)),
                ('account_opened', models.BooleanField(default=True)),
                ('last_login', models.CharField(max_length=45, null=True)),
            ],
            options={
                'db_table': 'user_table',
            },
        ),
    ]
