# Generated by Django 3.2.11 on 2022-03-01 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradingSystem', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertable',
            name='user_sex',
        ),
        migrations.AlterField(
            model_name='usertable',
            name='id_no',
            field=models.CharField(max_length=18, unique=True),
        ),
    ]
