# Generated by Django 3.2.11 on 2022-03-01 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradingSystem', '0002_auto_20220301_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertable',
            name='account_num',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='usertable',
            name='account_type',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='usertable',
            name='user_email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
