# Generated by Django 3.2.11 on 2022-02-25 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradingSystem', '0003_alter_usertable_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertable',
            name='phone_number',
            field=models.CharField(max_length=45, unique=True),
        ),
    ]
